// Edit this list to add, remove, reword, or reclassify bingo phrases.
// Every board draws 12 common, 8 uncommon, and 4 rare prompts.
window.BINGO_DATA = {
  balance: {
    common: 12,
    uncommon: 8,
    rare: 4
  },

  phrases: [
    { text: "Sassy Cop", tier: "common" },
    { text: "Cop says \"that's not how this works\"", tier: "common" },
    { text: "Impressive lungpower: screaming, yelling", tier: "common" },
    { text: "Over .20 BAC", tier: "rare" },
    { text: "Attempt to flee: running away, trying to escape", tier: "uncommon" },
    { text: "Repeating the same phrase 5x", tier: "common" },
    { text: "MAGA rage: \"I thought this was America,\" Donald Trump mentioned", tier: "rare" },
    { text: "Creates 3rd-party victims", tier: "uncommon" },
    { text: "Racism", tier: "common" },
    { text: "Status drop: \"Do you know who I am (or who I know)?\" Salary mentioned", tier: "common" },
    { text: "Demands to call someone (dad, president)", tier: "common" },
    { text: "Bring out the WRAP", tier: "rare" },
    { text: "Losing clothing items", tier: "uncommon" },
    { text: "Wisconsin", tier: "rare" },
    { text: "Switcheroo: person claiming to be the victim is the baddie", tier: "uncommon" },
    { text: "Blaming someone else for their predicament", tier: "common" },
    { text: "Violence against inanimate objects", tier: "uncommon" },
    { text: "\"I didn't do anything...\"", tier: "common" },
    { text: "Fluids: spitting, crying, peeing", tier: "common" },
    { text: "Misstates law or makes up rules", tier: "common" },
    { text: "\"You didn't read me my rights\"", tier: "common" },
    { text: "Innocent child or animal", tier: "uncommon" },
    { text: "Threatens to sue cops", tier: "common" },
    { text: "Attempts to negotiate", tier: "common" },
    { text: "Sovereign citizen behavior", tier: "uncommon" },
    { text: "Tool tornado", tier: "uncommon" },
    { text: "Florida", tier: "uncommon" },
    { text: "Wearing Dallas Cowboys apparel", tier: "rare" },
    { text: "Asks for vape", tier: "uncommon" },
    { text: "\"Why are you doing this to me?\"", tier: "common" },
    { text: "Feigning confusion", tier: "common" },
    { text: "\"We're past that point\"", tier: "uncommon" },
    { text: "Weaponizing mental illness or disability", tier: "uncommon" },
    { text: "Handcuffs clearly made of razor blades", tier: "rare" },
    { text: "Losing privileges due to bad behavior", tier: "common" },
    { text: "Purposely misunderstands something clear", tier: "common" },
    { text: "\"I'll be honest\" - proceeds to lie", tier: "common" },
    { text: "\"I wasn't...\" in reference to something they just did", tier: "common" },
    { text: "Behavior akin to demonic possession", tier: "uncommon" },
    { text: "Slips out of cuffs", tier: "rare" },
    { text: "Flirts with cops", tier: "rare" },
    { text: "\"You're gonna get another charge if you keep acting like this\"", tier: "common" },
    { text: "Spit hood", tier: "rare" },
    { text: "Demands supervisor", tier: "common" },
    { text: "Weaponizes mental illness", tier: "uncommon" },
    { text: "Wishes ill in the cop or their family", tier: "common" },
    { text: "Cookie monster fashion sense", tier: "uncommon" }
  ]
};
