// Edit this list to add, remove, or reword bingo phrases.
// The website randomly picks 24 unique entries for each new board.
window.BINGO_DATA = {
  phrases: [
    "Sassy Cop",
    "Cop says \"that's not how this works\"",
    "Impressive lungpower: screaming, yelling",
    "Over .20 BAC",
    "Attempt to flee: running away, trying to escape",
    "Repeating the same phrase 5x",
    "MAGA rage: \"I thought this was America,\" Donald Trump mentioned",
    "Creates 3rd-party victims",
    "Racism",
    "Status drop: \"Do you know who I am (or who I know)?\" Salary mentioned",
    "Demands to call someone (dad, president)",
    "Bring out the WRAP",
    "Losing clothing items",
    "Wisconsin",
    "Switcheroo: person claiming to be the victim is the baddie, blaming someone else for their predicament",
    "Violence against inanimate objects",
    "\"I didn't do anything...\"",
    "Fluids: spitting, crying, peeing",
    "Misstates law or makes up rules",
    "\"You didn't read me my rights\"",
    "Innocent child or animal",
    "Threatens to sue cops",
    "Attempts to negotiate",
    "Sovereign citizen behavior",
    "Tool tornado",
    "Florida",
    "Wearing Dallas Cowboys apparel",
    "Asks for vape",
    "\"Why are you doing this to me?\"",
    "Feigning confusion",
    "\"We're past that point\"",
    "Weaponizing mental illness or disability",
    "Handcuffs clearly made of razor blades",
    "Losing privileges due to bad behavior",
    "Purposely misunderstands something clear",
    "\"I'll be honest\" - proceeds to lie",
    "\"I wasn't...\" in reference to something they just did",
    "Behavior akin to demonic possession",
    "Slips out of cuffs",
    "Flirts with cops",
    "\"You're gonna get another charge if you keep acting like this\"",
    "Spit hood"
  ]
};
